# Generated by Django 4.0.6 on 2022-07-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.IntegerField(max_length=512, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=512)),
                ('role', models.CharField(max_length=512)),
            ],
        ),
    ]
