# Generated by Django 4.0.6 on 2022-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container_Registry',
            fields=[
                ('pro_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('registry_name', models.CharField(max_length=512)),
                ('create_time', models.CharField(max_length=512)),
                ('quota_size', models.IntegerField()),
            ],
        ),
    ]
