# Generated by Django 4.0.6 on 2022-08-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_container_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Container_Image',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
