# Generated by Django 4.0.6 on 2022-08-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_container_image_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container_registry',
            old_name='pro_id',
            new_name='project_id',
        ),
    ]
